### ISSUE TITLE
Send tx modal not working

### ISSUE THREAD

**Issue by theblackmace** [austintgriffith/eth.build#154]
I even tried to load Austin's version and with changed rpc url, and addresses but still not working.
I'm confident my implementation isn't the problem since the balance account modal is working fine. Also transaction object is being created fine as well

**Comment by theblackmace** [comment]
Anybody else facing this problem?

**Comment by edgeofinnerspace** [comment]
I think it has to do with the issue just below this that I also commented on. needs to be updated to use EIP-1559 transactions but right now it still has nodes that use legacy parameters for the TX json. but thats what im trying to fix for my own use. in the meantime check out "eth(_ or -)rebuild" forget if underscore or hyphen but shouldnt be hard to find. it doesnt help that no search engines actually work anymore. i miss altavista.

**Comment by theblackmace** [comment]
Thanks for the explanation, makes sense. :))
Also found eth_rebuild: https://github.com/Eth-Rebuild/eth_rebuild

**Comment by edgeofinnerspace** [comment]
Hey just saw the message, yea I forgot to mention eth rebuild. I cant get
either build or re to install though. If I manage to get dependencies in
place both repos end with the same error. Not in front of me right now but
something about "stdIn" being undefined if I'm remembering right!
