### ISSUE TITLE
Add a dropdown input for choosing which blockchain to connect to

### ISSUE THREAD

**Issue by jschiarizzi** [austintgriffith/eth.build#2]
## User story: 
I want to use mainnet eth blockchain in my eth.build flow. But I currently have to find a link to paste into a text input block. This is confusing and too hard for me to know what link to use for different options. 

## proposed:
A new block, in the _input_ tab called _Chain_. With a drop down that lets users choose between popular chains or insert a link to another one. Something like the select element in html

```
<select>
   <option>Ethereum Mainnet</option>
   <option>xdai POA Network</option>
   <option>etc etc</option>
   <option>other: opens insert text</option> 
</select>
```

**Comment by joaoaguiam** [comment]
@jschiarizzi You can now use the block "Chain" with a selection field. Please have a look at eth.build and check if it is what you were looking for.

**Comment by jschiarizzi** [comment]
Perfect. exactly what I needed
