### ISSUE TITLE
Components Menu Doesn't Appear in Narrow Screen Format

### ISSUE THREAD

**Issue by dghelm** [austintgriffith/eth.build#44]
After the 1000px break, the Components menu doesn't appear.

In actuality, it renders in the incorrect location, causing it to disappear before being seen.

**Comment by grahamtallen** [comment]
Will be fixed on the next deployment to sandbox.eth.build in the next few days

**Comment by grahamtallen** [comment]
Deployed! Thank you for the contribution @dghelm
