### ISSUE TITLE
I cannot connect to my local node 

### ISSUE THREAD

**Issue by Thaddeus19** [austintgriffith/eth.build#67]
I'm running **geth** locally with a private blockchain, it's http enabled to localhost on port 8545 but when I use it it doesn't recognize me, or does it query the chain.

For example, I query to test the block number with the blockchain module associating the chain module with localhost and it answers null, but if I change to Ropsten or mainnet it does the query. 

![error ethbuild](https://user-images.githubusercontent.com/51385192/125378202-efce5680-e353-11eb-809d-97c4feaf50d4.png)

**Comment by adnfx2** [comment]
I'm not an expert by any means but maybe you should try to run geth over LAN instead of localhost D:

**Comment by grahamtallen** [comment]
@Thaddeus19 any errors in the Console? network tab?

**Comment by grahamtallen** [comment]
Closing the issue for now

**Comment by Suedo** [comment]
I was facing same problem, and got it to work:

https://ethereum.stackexchange.com/a/121775/22522
