### ISSUE TITLE
iphone localstorage is weird

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/eth.build#7]
if you make changes on an iphone and reload, the changes are gone

but if you save, somehow that becomes what is loaded? 

something is strange with iphone and localstorage

**Comment by Polycarpik** [comment]
Steps to reproduce:
1. Grab an iphone.
2. Open eth.build in Safari. 
3. Do any change like moving blocks around or adding new blocks. 
4. Reload.

**Expected result:** after reload nothing changes, last state saved and you see the same blocks with the same positioning, including changes you did in step 3.

**Actual result:** after reloading you land to the initial state of the app – it contains only default address blocks, all changes made in step 3 are gone.

**Comment by Polycarpik** [comment]
@austintgriffith please close this one, I rewrote the same at https://github.com/austintgriffith/eth.build/issues/14
