### ISSUE TITLE
Cannot listen to ipfs subscribe on the default provided channel

### ISSUE THREAD

**Issue by grahamtallen** [austintgriffith/eth.build#75]
![Screen Shot 2021-08-15 at 12 00 45 PM](https://user-images.githubusercontent.com/14982690/129489463-de51275d-f2a5-42fd-a6ba-10fcf8193344.png)
See screenshot. the default provided channel cannot connect. If there is a better option for most people to have it working out of the box, we should set that one as the default.

```websocket.js:120 WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: 

index.js:67 Uncaught (in promise) Error: Couldn't listen on any of the servers
    at index.js:67
    at parallel.js:43
    at once.js:13
    at iteratorCallback (eachOf.js:65)
    at onlyOnce.js:13
    at parallel.js:40
    at index.js:59
    at f (once.js:24)```

**Comment by Aragar199** [comment]
Taking a look.

**Comment by Aragar199** [comment]
Have a working branch here https://github.com/austintgriffith/eth.build/pull/76

* websocket-star has been deprecated
* ipfs 0.39.0 is pretty old, updated to latest and lighter ipfs-core

I'm still seeing some topic errors so I'll still tinker with it for now.

**Comment by Aragar199** [comment]
Hey @grahamtallen, once I did the update I had to tweak some of the logic to make the IPFS nodes work. It's ready for review.

**Comment by grahamtallen** [comment]
I've tried installing with yarn and npm, for some reason no matter what I do, get a syntax error on this ipfs node module on this branch. @Aragar199 any ideas?

I'm node 14.17.3

```./node_modules/ipfs-core/src/ipns/publisher.js
SyntaxError: /Users/grahamallen/workdir/eth.build/node_modules/ipfs-core/src/ipns/publisher.js: Identifier directly after number (257:21)

  255 | 
  256 |     // Determinate the record sequence number
> 257 |     let seqNumber = 0n
      |                      ^
  258 | 
  259 |     if (record && record.sequence !== undefined) {
  260 |       seqNumber = !uint8ArrayEquals(record.value, value) ? BigInt(record.sequence) + 1n : BigInt(record.sequenc```

**Comment by grahamtallen** [comment]
Fixed merged, pending deployment

**Comment by MrWater98** [comment]
> (whoops, commented on the issue instead of the PR)
> 
> I've tried installing with yarn and npm, for some reason no matter what I do, get a syntax error on this ipfs node module on this branch. @Aragar199 any ideas?
> 
> I'm node 14.17.3
> 
> ```js
> SyntaxError: /Users/grahamallen/workdir/eth.build/node_modules/ipfs-core/src/ipns/publisher.js: Identifier directly after number (257:21)
> 
>   255 | 
>   256 |     // Determinate the record sequence number
> > 257 |     let seqNumber = 0n
>       |                      ^
>   258 | 
>   259 |     if (record && record.sequence !== undefined) {
>   260 |       seqNumber = !uint8ArrayEquals(record.value, value) ? BigInt(record.sequence) + 1n : BigInt(record.sequenc```
> ```

How to fix this problem?

**Comment by grahamtallen** [comment]
@MrWater98 yes! I have a fix for that on my fork. Let me show you.

**Comment by grahamtallen** [comment]
@MrWater98 https://github.com/grahamtallen/eth.build/pull/2

**Comment by MrWater98** [comment]
> @MrWater98 [grahamtallen#2](https://github.com/grahamtallen/eth.build/pull/2)

Could you explain more clearly, I have tried but all failed.

**Comment by MrWater98** [comment]
> > @MrWater98 [grahamtallen#2](https://github.com/grahamtallen/eth.build/pull/2)
> 
> Could you explain more clearly, I have tried but all failed.

I built succesfully by `git reset --hard 0c3e54a3d2d96afeb8ab2b4d9d4c7edcc3c3d0cf`, with command `yarnpkg` and `yarnpkg build` in Windows System. My node version is 14.17.3 and my yarnpkg version is 1.22.11.

**Comment by grahamtallen** [comment]
@MrWater98 the problem is caused by the npm package "react-scripts" version, you need to upgrade to 4.0.3, as suggested in my PR:     "react-scripts": "^4.0.3",
