### ISSUE TITLE
Large numbers displaying in e notaton

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/eth.build#78]
When 40000 * 10 ** 18 is displayed, it ends up in e notation.

It would be better if this displayed with all the zeros so it's easy to copy/paste into things like etherscan

example build: https://eth.build/build#9689940894e549986423b9bd3f44c91f5a77a79569180271cb015d06768dca4a

![image](https://user-images.githubusercontent.com/2653167/130134591-b1e6cdb1-6fb5-4a1b-8d40-d028bdfb6eb0.png)

**Comment by grahamtallen** [comment]
:eyes:

**Comment by grahamtallen** [comment]
@austintgriffith 
![Screenshot from 2021-08-20 14-58-22](https://user-images.githubusercontent.com/14982690/130297350-91045810-d5ff-4a45-809f-c0c0828043a3.png)
